### ISSUE TITLE
preview token visibility

### ISSUE THREAD

**Issue by gutisalex** [whitep4nth3r/nextjs-contentful-blog-starter#16]
may I ask why you have put the preview token to the client side (NEXT_PUBLIC_)?

I am just curious because I read that those credentials should not be exposed to the client side due to everyone can access this. But I use react query and the graphql client to get my data from contentful and in order to react query to work I need to make them public. I think the refetching with react query happens on the client side?! But maybe I didnt fully understand it...

What do you think?

**Comment by whitep4nth3r** [comment]
Great question!

I think the short answer is that I forgot to change the environment variable name when I moved the preview functionality to the server. All the preview functionality happens on the server, so shouldn't need the `NEXT_PUBLIC_` prefix. At least I hope... I have no way of testing this right now 😀. 

This has been addressed in the [latest commit](https://github.com/whitep4nth3r/nextjs-contentful-blog-starter/commit/9ee0afbdf31caa490bf92ec164418dbb65d1e067).

Regarding the access token, unless you have the secret as well, it's useless. So exposing the access token was OK in this case.

You want to avoid making both the secret and access token public on the client. I'm sorry I don't have any experience with React Query. Generating your site at build time into static pages would also get around the issue with React only working on the client, that's why Next.js and static site generators are good for this use case. Alternatively, you could look into ways you can fetch data on a server, such as with using serverless functions, depending on your hosting platform and what it supports.

It's also worth mentioning that this starter is around 2 years old, Next.js has moved on considerably, and I don't actively maintain the repo.

Have a great day!

**Comment by gutisalex** [comment]
thanks for the quick response! It is correct, unless you don't have the secret it's useless via browser but if you have the spaceId and the token you can just use a graphqlclient to fetch the data... ;) But you didn't expose the spaceId. But I have to... :( I think serverless functions is the way here to be 100% secure... thanks a lot! 

Have a nice day, too!
